version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    container_name: task_manager_prod
    restart: unless-stopped
    working_dir: /var/www
    networks:
      - task_network
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: task_manager_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: task_manager
    ports:
      - "5432:5432"
    networks:
      - task_network

  nginx:
    image: nginx:alpine
    container_name: task_manager_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./../../:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - task_network

networks:
  task_network:
    driver: bridge
